sudo: required
services:
  - docker

before_install:
  - docker build -t rohitkhatri/react-app:dev -f Dockerfile.dev .

script:
  - docker run -e CI=true rohitkhatri/react-app:dev npm run test

# deploy:
#   provider: elasticbeanstalk
#   region : "us-east-2"
#   app: "react-app"
#   env: "ReactApp-env"
#   bucket_name: "elasticbeanstalk-us-east-2-635148058219"
#   bucket_path: "react-app"
#   on:
#     branch: master