sudo: required
services:
  - docker

before_install:
  - docker build -t rohitkhatri/react-app:dev -f docker/Dockerfile.dev frontend

script:
  - docker run rohitkhatri/react-app:dev npm run tests -- --coverage